baseURL = 'https://dan.bodar.com/'
languageCode = 'en-gb'
defaultContentLanguage = "en"
title = 'Yesterday I was wrong'
enableEmoji = true
theme = "poison"

[permalinks]
  posts = '/:year/:month/:day/:slug/'

[params]
  brand = "Yesterday I was wrong"
  description = "Daniel Worthington-Bodart's technical blog"
  menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]